"""Add last edited column

Revision ID: ff8600b8816f
Revises: 666a5731dac7
Create Date: 2025-06-28 15:19:17.568075

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from sqlalchemy.sql import func

# revision identifiers, used by Alembic.
revision: str = 'ff8600b8816f'
down_revision: Union[str, Sequence[str], None] = '666a5731dac7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notes', 
        sa.Column('last_edited',
        sa.DateTime(timezone=True), 
        server_default=sa.text('now()'),
        onupdate=func.now(),
        nullable=False)
    )
    op.alter_column('notes', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_notes_id'), table_name='notes')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_notes_id'), 'notes', ['id'], unique=False)
    op.alter_column('notes', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_column('notes', 'last_edited')
    # ### end Alembic commands ###
